puts "The students of my cohort at Makers Academy"
puts "-------------------------------------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Micheal Corleone"
puts "Alex De Large"
puts "The Alien"
puts "Terminator"
puts "Freedy Kruger"
puts "The Joker"
